name = "Create New Horizon"
author = "mo_guang"
version = "1.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e808a2957efcfc0614f05c08933c26cb022317c0ebf0445d909ace6139eb3718"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
