ServerEvents.recipes(event => {

    //天顶激光蚀刻机——反相蚀刻配方
    let ctnh = event.recipes.gtceu
        //泰拉催化剂
    event.recipes.gtceu.phase_inversion("zenith_soc_inverse")
        .itemInputs('kubejs:zenith_soc')
        .itemInputs('gtceu:soc_wafer')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 400))
        .itemOutputs('kubejs:zenith_wafer')
        .duration(4000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("mana_soc_inverse")
        .itemInputs('kubejs:mana_soc')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 100))
        .itemOutputs('kubejs:mana_wafer')
        .duration(2000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("mpic_reverse")
        .itemInputs('gtceu:mpic_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 60))
        .itemOutputs('gtceu:mpic_wafer')
        .duration(2000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("hpic_reverse")
        .itemInputs('gtceu:hpic_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 120))
        .itemOutputs('gtceu:hpic_wafer')
        .duration(3000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("uhpic_reverse")
        .itemInputs('gtceu:uhpic_chip')
        .itemInputs('gtceu:hpic_wafer')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 360))
        .itemOutputs('gtceu:uhpic_wafer')
        .duration(6000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("ilc_reverse")
        .itemInputs('gtceu:ilc_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 60))
        .itemOutputs('gtceu:ilc_wafer')
        .duration(2000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("nand_reverse")
        .itemInputs('gtceu:nand_memory_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 80))
        .itemOutputs('gtceu:nand_memory_wafer')
        .duration(3000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("nor_reverse")
        .itemInputs('gtceu:nor_memory_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 80))
        .itemOutputs('gtceu:nor_memory_wafer')
        .duration(3000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("cpu_reverse")
        .itemInputs('gtceu:cpu_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 60))
        .itemOutputs('gtceu:cpu_wafer')
        .duration(2000)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("nano_cpu_reverse")
        .itemInputs('gtceu:nano_cpu_chip')
        .itemInputs('gtceu:cpu_wafer')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 120))
        .itemOutputs('gtceu:nano_cpu_wafer')
        .duration(3500)
        .EUt(480)
    event.recipes.gtceu.phase_inversion("qbit_cpu_reverse")
        .itemInputs('gtceu:qbit_cpu_chip')
        .itemInputs('gtceu:nano_cpu_wafer')
        .inputFluids(Fluid.of("gtceu:radon", 240))
        .itemInputs('gtceu:cpu_wafer')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 120))
        .itemOutputs('gtceu:qbit_cpu_wafer')
        .duration(5000)
        .EUt(480)

    event.recipes.gtceu.phase_inversion("ram_reverse")
        .itemInputs('gtceu:ram_chip')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 60))
        .itemOutputs('gtceu:ram_wafer')
        .duration(2000)
        .EUt(480)
})