ServerEvents.recipes(event => {
    //天顶源质和天顶机器的配方
    //不要把天顶机器特殊配方放进这里，单开一个文件去放
    event.recipes.gtceu.mana_reactor('zenith')
        .itemInputs('apotheosis:infused_breath')
        .itemInputs("ars_nouveau:source_gem_block")
        .inputFluids(Fluid.of("gtceu:mana", 10000))
        .inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 10000))
        .inputFluids(Fluid.of("gtceu:krypton", 1000))
        .outputFluids(Fluid.of("gtceu:zenith_essence", 2000))
        .duration(400)
        .EUt(6666)
    event.recipes.gtceu.assembly_line('zenith_laser')
        .itemInputs('16x ctnhcore:zenith_casing_gearbox')
        .itemInputs('16x gtceu:mana_plus_gear')
        .itemInputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .itemInputs('8x gtceu:iv_emitter')
        .itemInputs('2x gtceu:iv_electric_piston')
        .itemInputs('4x gtceu:laser_safe_engraving_casing')
        .itemInputs('4x gtceu:large_engraving_laser')
        .itemInputs('32x gtceu:uhpic_chip')
        .itemInputs('16x gtceu:mana_super_plus_gear')
        .itemInputs('8x ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:twist_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_laser')
        .duration(1200)
        .EUt(12222)
    event.recipes.gtceu.assembly_line("ctnhcore:zenith_circult_assembler")
        .itemInputs('4x gtceu:luv_conveyor_module')
        .itemInputs('32x gtceu:small_mana_super_plus_gear')
        .itemInputs('16x #gtceu:circuits/zpm')
        .itemInputs('16x ctnhcore:zenith_casing_gearbox')
        .itemInputs('8x gtceu:luv_robot_arm')
        .itemInputs('32x gtceu:mana_plus_screw')
        .itemInputs('32x gtceu:naquadah_foil')
        .itemInputs('4x gtceu:large_assembler')
        .itemInputs('16x gtceu:ultra_mana_gear')
        .itemInputs('8x ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_circult_assembler')
        .EUt(44444)
        .duration(2000)
    event.recipes.gtceu.assembly_line("ctnhcore:zenith_distillation_tower")
        .itemInputs('8x gtceu:luv_electric_pump')
        .itemInputs('12x gtceu:naquadah_large_fluid_pipe')
        .itemInputs('8x #gtceu:circuits/luv')
        .itemInputs('4x ctnhcore:zenith_casing_gearbox')
        .itemInputs('gtceu:large_distillery')
        .itemInputs('32x gtceu:mana_plus_screw')
        .itemInputs('16x gtceu:distillation_tower')
        .itemInputs('4x ctnhcore:horizen_rune')
        .itemInputs('8x ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_distillation_tower')
        .EUt(12222)
        .duration(800)
})