
[avaritia]
	#Probability of a neutron pile is dropped by condensing modifier
	condensingDropProbability = 0.003

[mekanism]
	#Allow Mekaplate can use shield of electricity
	mekaplateUseShield = true

[apotheosis]
	#Maximum level of enchantments granted by override
	overrideLevelLimit = 255

#Provided by AddonAPI:
#Other Mod Compat Options
[compat]
	"Draconic Evolution Compat" = true
	"CC:Tweaked Compat" = true
	"Mekanism Compat" = true
	"ProjectE Compat" = true
	"Avaritia Compat" = true
	"Tinkers' Things Compat" = true
	"Apotheosis Compat" = true
	"Sakura Tinker Compat" = true
	"Iron's Spells n' Spellbooks Compat" = true
	"Psi Compat" = true
	"SlashBlade Compat" = true
	"Create Compat" = true
	"TaCz Compat" = true
	"Curios API Compat" = true

#General
[general]
	#Using ticex-more-config.toml(If true, it will override your datapack!)
	useMoreConfig = true
	#MAX Rate Capacity of RF Furnace(RF/t)
	rateCapacity = 100000

[curios]
	#Ticks remaining on the gauntlet after a gauntlet shot hits
	gantletRemainTicks = 40
	#Blacklist of entities that do not drop the glove.
	gloveDropBlacklist = ["minecraft:armor_stand", "dummmmmmy:target_dummy"]
	#Use gloveDropBlacklist as whitelist
	gloveDropBlacklistAsWhitelist = false

