ServerEvents.recipes(event => {
    remove_recipes_type(event, ['biomancy:bio_brewing'])
    
    event.replaceOutput({type:"biomancy:decomposing"}, 'biomancy:stone_powder', "gtceu:stone_dust")
    
    remove_recipes_id(event, [
        "biofactory:mixing/nutrients_fluid_from_paste",
        "gtceu:circuit_assembler/wetware_processor_luv",
        "gtceu:circuit_assembler/wetware_processor_luv_soldering_alloy",
        "gtceu:circuit_assembler/wetware_processor_assembly_zpm",
        "gtceu:circuit_assembler/wetware_processor_assembly_zpm_soldering_alloy",
        "gtceu:assembly_line/wetware_super_computer_uv",
        "gtceu:assembly_line/wetware_mainframe_uhv",
        
        
        "biomancy:crafting/primordial_core",
        "biomancy:bio_brewing",
        "biomancy:crafting/despoil_sickle",
        "biomancy:crafting/primordial_cradle",
        "biomancy:primordial_cradle_cleansing.cleansed",
        "biomancy:bio_forging/decomposer",

        "biomancy:bio_forging/flesh",
        "biomancy:bio_forging/flesh_pillar",
        "biomancy:bio_forging/acolyte_armor_boots",
        "biomancy:bio_forging/packed_flesh",
        "biomancy:bio_forging/ornate_flesh",
        "biomancy:bio_forging/mascot_patterns",
        "biomancy:bio_forging/storage_sac",
        "biomancy:bio_forging/mob_fang",
        "biomancy:bio_forging/flesh_fence",
        "biomancy:bio_forging/leather",
        "biomancy:bio_forging/flesh_stairs",
        "biomancy:bio_forging/tubular_flesh",
        "biomancy:bio_forging/bone",
        "biomancy:bio_forging/impermeable_membrane",
        "biomancy:bio_forging/acolyte_armor_leggings",
        "biomancy:bio_forging/adult_permeable_membrane_pane",
        "biomancy:bio_forging/fibrous_flesh",
        "biomancy:bio_forging/nautilus_shell",
        "biomancy:bio_forging/tendon_chain",
        
        "biomancy:bio_forging/impermeable_membrane_pane",
        "biomancy:bio_forging/ravenous_claws",
        "biomancy:bio_forging/bio_lab",
        "biomancy:bio_forging/scute",
        "biomancy:bio_forging/piglin_head",
        "biomancy:bio_forging/flesh_slab",
        "biomancy:bio_forging/thorn_shield",
        "biomancy:bio_forging/flesh_door",
        "biomancy:bio_forging/chrysalis",
        "biomancy:bio_forging/fertilizer",
        "biomancy:bio_forging/player_head",
        "biomancy:bio_forging/caustic_gunblade",
        "biomancy:bio_forging/acolyte_armor_helmet",
        "biomancy:bio_forging/digester",
        "biomancy:bio_forging/fleshkin_chest",
        "biomancy:bio_forging/flesh_wall",
        "biomancy:bio_forging/wither_skeleton_skull",
        "biomancy:bio_forging/fibrous_flesh_slab",
        "biomancy:bio_forging/flesh_ladder",
        "biomancy:bio_forging/extractor",
        "biomancy:bio_forging/baby_permeable_membrane_pane",
        "biomancy:bio_forging/string",
        "biomancy:bio_forging/chiseled_flesh",
        "biomancy:bio_forging/undead_permeable_membrane",

        "biomancy:bio_forging/baby_permeable_membrane",
        "biomancy:bio_forging/modular_larynx",
        "biomancy:bio_forging/fibrous_flesh_wall",
        "biomancy:bio_forging/shroomlight",
        "biomancy:bio_forging/fibrous_flesh_stairs",
        "biomancy:bio_forging/adult_permeable_membrane",
        "biomancy:bio_forging/biometric_membrane",

        "biomancy:bio_forging/vial",
        "biomancy:bio_forging/skeleton_skull",
        "biomancy:bio_forging/packed_flesh_wall",
        "biomancy:bio_forging/flesh_fence_gate",
        "biomancy:bio_forging/undead_permeable_membrane_pane",
        "biomancy:bio_forging/full_flesh_door",
        "biomancy:bio_forging/cobweb",
        "biomancy:bio_forging/ornate_flesh_slab",

        "biomancy:bio_forging/packed_flesh_stairs",
        "biomancy:bio_forging/mob_claw",
        "biomancy:bio_forging/acolyte_armor_chestplate",
        "biomancy:bio_forging/creator_mix",

        "biomancy:bio_forging/injector",
        "biomancy:bio_forging/packed_flesh_slab",
        "biomancy:bio_forging/flesh_iris_door",
    ])
})