ServerEvents.recipes(event => {
    let ctnh = event.recipes.gtceu
    ctnh.assembler('ctnhcore:mana_generator_turbine_tier3')
        .itemInputs('ctnhcore:mana_generator_turbine_tier2')
        .itemInputs('kubejs:general_circuit_luv')
        .itemInputs('gtceu:extreme_combustion_engine')
        .itemInputs('mythicbotany:muspelheim_rune')
        .itemInputs('4x gtceu:terra_steel_gear')
        .itemOutputs('ctnhcore:mana_generator_turbine_tier3')
        .inputFluids('gtceu:mana_stable_cooldown 10000')
        .EUt(7680)
        .duration(200)

    ctnh.assembly_line('ctnhcore:mana_generator_turbine_tier4')
        .itemInputs('ctnhcore:mana_generator_turbine_tier1')
        .itemInputs('ctnhcore:mana_generator_turbine_tier2')
        .itemInputs('ctnhcore:mana_generator_turbine_tier3')
        .itemInputs('gtceu:plasma_large_turbine')
        .itemInputs('64x gtceu:mana_steel_gear')
        .itemInputs('32x gtceu:elementium_gear')
        .itemInputs('16x gtceu:terra_steel_gear')
        .itemInputs('8x gtceu:alfsteel_gear')
        .itemInputs('4x gtceu:mana_plus_gear')
        .itemInputs('2x gtceu:mana_super_plus_gear')
        .itemInputs('botania:rune_fire')
        .itemInputs('botania:rune_summer')
        .itemInputs('botania:rune_wrath')
        .itemInputs('botania:rune_wrath')
        .itemInputs('ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:alfsteel_casing')
        .inputFluids('gtceu:molten_cerrobase_140 16000')
        .inputFluids('gtceu:mana_stable_cooldown 16000')
        .itemOutputs('ctnhcore:mana_generator_turbine_tier4')
        .EUt(7680 * 4)
        .duration(400)

    event.recipes.gtceu.mana_generator('gtceu:blood_fuel')
        .inputFluids('gtceu:blood_fuel 6666')
        .EUt(-32)
        .outputFluids('bloodmagic:life_essence_fluid 6666')
        .duration(80)
    event.recipes.gtceu.mana_generator('gtceu:blood_fuel_active')
        .inputFluids('gtceu:blood_fuel_active 666')
        .EUt(-78)
        .outputFluids('gtceu:blood_fuel_exhausted 666')
        .duration(100)
    event.recipes.gtceu.mana_generator('gtceu:elf_fuel')
        .inputFluids('gtceu:elf_fuel 100')
        .EUt(-64)
        .outputFluids('gtceu:mana 5')
        .outputFluids('gtceu:neon 10')
        .duration(200)
    event.recipes.gtceu.mana_generator('gtceu:elf_active_fuel')
        .inputFluids('gtceu:elf_active_fuel 100')
        .EUt(-108)
        .outputFluids('gtceu:mana_stable_cooldown 3')
        .outputFluids('gtceu:elf_fuel 1')
        .duration(200)
    event.recipes.gtceu.mana_generator('gtceu:starlight_fuel')
        .inputFluids('gtceu:starlight_fuel 100')
        .EUt(-128)
        .outputFluids('gtceu:mana_stable_cooldown 6')
        .duration(120)
    event.recipes.gtceu.mana_generator('gtceu:starlight_fuel_active')
        .inputFluids('gtceu:starlight_fuel_active 100')
        .EUt(-168)
        .outputFluids('gtceu:starlight_fuel_exhausted 100')
        .duration(240)
    event.recipes.gtceu.mana_generator('gtceu:mana_up_fuel_active')
        .inputFluids('gtceu:mana_up_fuel_active 100')
        .EUt(-384)
        .outputFluids('gtceu:mana_up_fuel_exhausted 100')
        .duration(280)
    event.recipes.gtceu.mana_generator('gtceu:mana_up_fuel')
        .inputFluids('gtceu:mana_up_fuel 100')
        .EUt(-128)
        .outputFluids('gtceu:mana_up_fuel 5')
        .duration(120)

})