ServerEvents.recipes(event => {
    //一般的魔力反应器配方
    //只有在其他地方都不适合放且是老配方时再使用这个文件
    //！不要移植Botania.js的史山到这里面，除非你有足够的把握不会出BUG1!
    let ctnh = event.recipes.gtceu
        //泰拉催化剂
    event.recipes.gtceu.mana_reactor("terria_catalyst")
        .itemInputs("64x mythicbotany:alfsteel_ingot")
        .itemInputs("64x botania:gaia_ingot")
        .itemInputs("64x mythicbotany:niflheim_rune")
        .itemInputs("64x botania:rune_mana")
        .itemInputs("kubejs:elf_catalyst")
        .inputFluids(Fluid.of("gtceu:mana", 1024000))
        .chancedOutput('kubejs:terria_catalyst', 5000, 2000)
        .itemOutputs("kubejs:elf_catalyst")
        .duration(6000)
        .EUt(960)
        //精灵钢
    event.recipes.gtceu.mana_reactor('alfsteel1')
        .circuit(0)
        .itemInputs("botania:elementium_ingot")
        .itemInputs("botania:elf_glass")
        .itemInputs('botania:dragonstone')
        .itemInputs('botania:quartz_elven')
        .inputFluids(Fluid.of("gtceu:mana", 10000))
        .chancedOutput('mythicbotany:alfsteel_ingot', 5000, 100)
        .duration(1600)
        .EUt(480)
    event.recipes.gtceu.mana_reactor('alfsteel2')
        .circuit(1)
        .itemInputs("botania:elementium_ingot")
        .itemInputs("botania:elf_glass")
        .itemInputs('botania:dragonstone')
        .itemInputs('botania:quartz_elven')
        .notConsumable('kubejs:elf_catalyst')
        .inputFluids(Fluid.of("gtceu:mana", 8000))
        .chancedOutput('mythicbotany:alfsteel_ingot', 7500, 100)
        .duration(800)
        .EUt(1680)
    event.recipes.gtceu.mana_reactor('alfsteel3')
        .circuit(2)
        .itemInputs("botania:elementium_ingot")
        .itemInputs("botania:elf_glass")
        .itemInputs('botania:dragonstone')
        .itemInputs('botania:quartz_elven')
        .notConsumable('kubejs:terria_catalyst')
        .inputFluids(Fluid.of("gtceu:mana", 4000))
        .itemOutputs('mythicbotany:alfsteel_ingot')
        .duration(200)
        .EUt(7280)
        //精灵转化
    event.recipes.gtceu.mana_reactor('pixie_dust')
        .itemInputs('1x botania:mana_pearl')
        .notConsumable('kubejs:elf_catalyst')
        .inputFluids(Fluid.of("gtceu:mana", 500))
        .itemOutputs('botania:pixie_dust')
        .duration(100)
        .EUt(480)
    event.recipes.gtceu.mana_reactor('elf_glass')
        .itemInputs('botania:mana_glass')
        .notConsumable('kubejs:elf_catalyst')
        .inputFluids(Fluid.of("gtceu:mana", 500))
        .itemOutputs("botania:elf_glass")
        .duration(100)
        .EUt(480)
    event.recipes.gtceu.mana_reactor('dragonstone')
        .itemInputs('2x botania:mana_diamond')
        .notConsumable('kubejs:elf_catalyst')
        .inputFluids(Fluid.of("gtceu:mana", 500))
        .itemOutputs('botania:dragonstone')
        .duration(100)
        .EUt(480)
    event.recipes.gtceu.mana_reactor("rainbow_block")
        .itemInputs("botania:elf_glass")
        .notConsumable('botania:rainbow_rod')
        .itemOutputs("botania:bifrost_perm")
        .EUt(30)
        .duration(40)
        //盖亚反应器
    event.recipes.gtceu.gaia_reactor("gaia1")
        .itemInputs("botania:terrasteel_ingot")
        .itemOutputs("4x botania:life_essence")
        .itemOutputs("10x botania:manasteel_ingot")
        .itemOutputs("5x botania:mana_diamond")
        .itemOutputs("5x botania:mana_pearl")
        .outputFluids(Fluid.of("gtceu:mana", 1000))
        .chancedOutput("botania:rune_water", 2500, 250)
        .chancedOutput("botania:rune_fire", 2500, 250)
        .chancedOutput("botania:rune_earth", 2500, 250)
        .chancedOutput("botania:rune_air", 2500, 250)
        .chancedOutput("botania:rune_spring", 1500, 150)
        .chancedOutput("botania:rune_summer", 1500, 150)
        .chancedOutput("botania:rune_autumn", 1500, 150)
        .chancedOutput("botania:rune_winter", 1500, 150)
        .duration(400)
        .EUt(480)

    event.recipes.gtceu.gaia_reactor("gaia2")
        .itemInputs("botania:gaia_ingot")
        .itemOutputs("16x botania:life_essence")
        .itemOutputs("12x botania:manasteel_ingot")
        .itemOutputs("8x botania:mana_diamond")
        .itemOutputs("8x botania:mana_pearl")
        .itemOutputs("2x botania:terrasteel_ingot")
        .itemOutputs("4x botania:dragonstone")
        .outputFluids(Fluid.of("gtceu:mana", 10000))
        .chancedOutput("botania:rune_water", 5000, 500)
        .chancedOutput("botania:rune_fire", 5000, 500)
        .chancedOutput("botania:rune_earth", 5000, 500)
        .chancedOutput("botania:rune_air", 5000, 500)
        .chancedOutput("botania:rune_spring", 3000, 300)
        .chancedOutput("botania:rune_summer", 3000, 300)
        .chancedOutput("botania:rune_autumn", 3000, 300)
        .chancedOutput("botania:rune_winter", 3000, 300)
        .chancedOutput("botania:rune_lust", 2000, 200)
        .chancedOutput("botania:rune_gluttony", 2000, 200)
        .chancedOutput("botania:rune_greed", 2000, 200)
        .chancedOutput("botania:rune_sloth", 2000, 200)
        .chancedOutput("botania:rune_wrath", 2000, 200)
        .chancedOutput("botania:rune_envy", 2000, 200)
        .chancedOutput("botania:rune_pride", 2000, 200)
        .duration(800)
        .EUt(1920)
    event.recipes.gtceu.gaia_reactor("gaia3")
        .itemInputs("mythicbotany:alfsteel_ingot")
        .itemOutputs('4x botania:elementium_ingot')
        .itemOutputs('2x botania:rune_mana')
        .outputFluids(Fluid.of("gtceu:mana", 45000))
        .chancedOutput("mythicbotany:vanaheim_rune", 2000, 2000)
        .chancedOutput("mythicbotany:alfheim_rune", 2000, 2000)
        .chancedOutput('mythicbotany:joetunheim_rune', 2000, 2000)
        .chancedOutput('mythicbotany:helheim_rune', 2000, 2000)
        .chancedOutput('mythicbotany:nidavellir_rune', 2000, 2000)
        .chancedOutput('mythicbotany:midgard_rune', 2000, 2000)
        .chancedOutput('mythicbotany:niflheim_rune', 2000, 2000)
        .chancedOutput('mythicbotany:muspelheim_rune', 2000, 2000)
        .chancedOutput('mythicbotany:asgard_rune', 2000, 2000)
        .chancedOutput('mythicbotany:alfsteel_ingot', 2000, 100)

    .duration(1200)
        .EUt(7680)
})