ServerEvents.recipes(event => {
    //存放着所有魔力燃料配方
    let ctnh = event.recipes.gtceu
    //event.recipes.gtceu.assembler('ctnhcore:magic_fuel_generator')
    //    .itemInputs('ctnhcore:fuel_refining_factory')
    //    .itemInputs('64x gtceu:alfsteel_gear')
    //    .itemInputs('botania:pure_daisy')
    //    .itemInputs('mythicbotany:wither_aconite')
    //    .itemInputs('botania:gourmaryllis')
    //    .itemInputs('botania:shulk_me_not')
    //    .itemInputs('botania:rosa_arcana')
    //    .itemInputs('ctnhcore:osmiridium_casing')
    //    .itemOutputs('ctnhcore:magic_fuel_generator')
    //    .inputFluids(Fluid.of('gtceu:zenith_essence', 1000))
    //    .EUt(8192)
    //    .duration(1000)

    //魔力稳定剂
    //event.recipes.gtceu.magic_fuel_generator('mana_stable_cooldown')
    //    .inputFluids(Fluid.of('gtceu:pcb_coolant', 5000))
    //    .inputFluids(Fluid.of('gtceu:elf_fuel', 5000))
    //    .inputFluids(Fluid.of('gtceu:cryotheum', 5000))
    //    .inputFluids('gtceu:neon 5000')
    //    .itemInputs('mythicbotany:niflheim_rune')
    //    .outputFluids(Fluid.of('gtceu:mana_stable_cooldown', 25000))
    //    .EUt(32678)
    //   .duration(200);
    //vent.recipes.gtceu.large_chemical_reactor('mana_stable_cooldown')
    //    .inputFluids(Fluid.of('gtceu:pcb_coolant', 1000))
    //    .inputFluids(Fluid.of('gtceu:neon', 1000))
    //    .inputFluids(Fluid.of('gtceu:elf_fuel', 1000))
    //    .inputFluids(Fluid.of('gtceu:cryotheum', 1000))
    //    .itemInputs('mythicbotany:niflheim_rune')
    //    .outputFluids(Fluid.of('gtceu:mana_stable_cooldown', 5000))
    //    .EUt(960)
    //    .duration(200);
    //精灵燃料
    //event.recipes.gtceu.large_chemical_reactor('gtceu:elf_fuel')
    //    .inputFluids(Fluid.of("gtceu:mana", 5000))
    //    .inputFluids(Fluid.of("gtceu:carbon_dioxide", 2000))
    //    .inputFluids(Fluid.of("gtceu:argon", 1000))
    //    .inputFluids(Fluid.of('gtceu:neon', 1000))
    //    .outputFluids(Fluid.of("gtceu:elf_fuel", 5000))
    //    .duration(500)
    //    .EUt(760)
    //event.recipes.gtceu.mana_reactor("elf_fuel_active")
    //    .chancedInput('botania:pure_daisy', 2000, -1000)
    //    .itemInputs('16x gtceu:elementium_dust')
    //    .itemInputs('1x mythicbotany:alfheim_rune')
    //    .itemInputs('4x gtceu:industrial_tnt')
    //    .inputFluids(Fluid.of('gtceu:elf_fuel', 1440))
    //    .inputFluids(Fluid.of('gtceu:mana', 7200))
    //    .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
    //    .outputFluids(Fluid.of('gtceu:elf_active_fuel', 2880))
    //    .EUt(8192)
    //4   .duration(200)
    event.recipes.gtceu.magic_fuel_generator('gtceu:elf_fuel')
        .inputFluids(Fluid.of("gtceu:mana", 50000))
        .inputFluids(Fluid.of("gtceu:carbon_dioxide", 20000))
        .inputFluids(Fluid.of("gtceu:argon", 10000))
        .outputFluids(Fluid.of("gtceu:elf_fuel", 50000))
        .duration(500)
        .EUt(760)
    event.recipes.gtceu.magic_fuel_generator("elf_fuel_active_2")
        .itemInputs('16x gtceu:elementium_dust')
        .itemInputs('1x mythicbotany:alfheim_rune')
        .itemInputs('4x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:elf_fuel', 1640))
        .inputFluids(Fluid.of('gtceu:mana_plus', 1440))
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
        .outputFluids(Fluid.of('gtceu:elf_active_fuel', 8400))
        .EUt(8192)
        .duration(200)
        //精灵行星燃料
    event.recipes.gtceu.magic_fuel_generator('elf_planet_fuel')
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .itemInputs('mythicbotany:muspelheim_rune')
        .inputFluids(Fluid.of('gtceu:liquid_alfheim_air', 17280))
        .inputFluids(Fluid.of('gtceu:vibrant_alloy', 2880))
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
        .outputFluids(Fluid.of('gtceu:starlight_fuel', 1728))
        .EUt(32678)
        .duration(200)
    event.recipes.gtceu.mana_reactor('elf_planet_fuel')
        .chancedInput("botania:pure_daisy", 2500, -1250)
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .itemInputs('mythicbotany:muspelheim_rune')
        .inputFluids(Fluid.of('gtceu:liquid_alfheim_air', 14400))
        .inputFluids(Fluid.of('gtceu:vibrant_alloy', 2880))
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
        .outputFluids(Fluid.of('gtceu:starlight_fuel', 1440))
        .EUt(32678)
        .duration(200)
    event.recipes.gtceu.magic_fuel_generator('elf_planet_fuel_active_1')
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .itemInputs('gtceu:quantum_star')
        .itemInputs('32x gtceu:gelled_toluene')
        .inputFluids(Fluid.of('gtceu:starlight_fuel', 1440))
        .inputFluids(Fluid.of('gtceu:vibrant_alloy', 2880))
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
        .outputFluids(Fluid.of('gtceu:starlight_fuel_active', 3220))
        .EUt(32678)
        .duration(400)
    event.recipes.gtceu.mana_reactor('elf_planet_fuel_active_2')
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .itemInputs('gtceu:quantum_star')
        .itemInputs('32x gtceu:gelled_toluene')
        .inputFluids(Fluid.of('gtceu:starlight_fuel', 1440))
        .inputFluids(Fluid.of('gtceu:vibrant_alloy', 2880))
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 288))
        .outputFluids(Fluid.of('gtceu:starlight_fuel_active', 2880))
        .EUt(32678)
        .duration(400)

    //恶魔意志燃料
    event.recipes.gtceu.magic_fuel_generator('gtceu:blood_fuel')
        .outputFluids('gtceu:blood_fuel 66666')
        .itemInputs('6x bloodmagic:defaultcrystal')
        .addData("addlp", 66666)
        .EUt(7680)
        .duration(80)
    event.recipes.gtceu.mana_reactor('gtceu:blood_fuel_active')
        .inputFluids(Fluid.of('gtceu:blood_fuel', 6666))
        .itemInputs('4x bloodmagic:defaultcrystal')
        .chancedInput('kubejs:endslate', 3000, -1000)
        .EUt(6666)
        .duration(400)
        .outputFluids(Fluid.of('gtceu:blood_fuel_active', 9999))
    event.recipes.gtceu.magic_fuel_generator('gtceu:blood_fuel_active')
        .inputFluids(Fluid.of('gtceu:blood_fuel', 7777))
        .itemInputs('4x bloodmagic:defaultcrystal')
        .EUt(6666)
        .duration(400)
        .outputFluids(Fluid.of('gtceu:blood_fuel_active', 11111))
    event.recipes.gtceu.mana_reactor('gtceu:blood_fuel_active_recycle')
        .inputFluids(Fluid.of('gtceu:blood_fuel_exhausted', 16666))
        .itemInputs('4x bloodmagic:defaultcrystal')
        .chancedInput('kubejs:endslate', 5000, -100)
        .EUt(6666)
        .duration(200)
        .outputFluids(Fluid.of('gtceu:blood_fuel_active', 16666))
    event.recipes.gtceu.magic_fuel_generator('gtceu:blood_fuel_active_recycle')
        .inputFluids(Fluid.of('gtceu:blood_fuel_exhausted', 16666))
        .itemInputs('4x bloodmagic:defaultcrystal')
        .EUt(6666)
        .duration(800)
        .outputFluids(Fluid.of('gtceu:blood_fuel_active', 16666))

    event.recipes.gtceu.mana_reactor('gtceu:mana_up_fuel')

    .outputFluids(Fluid.of('gtceu:mana_up_fuel', 1440))
        .inputFluids(Fluid.of('gtceu:starlight_fuel', 720))
        .inputFluids(Fluid.of('gtceu:blood_fuel', 720))
        .inputFluids(Fluid.of('gtceu:zenith_essence', 720))
        .itemInputs('32x gtceu:gelled_toluene')
        .itemInputs('gtceu:naquadah_dust')
        .itemInputs('4x gtceu:ultra_mana_dust')
        .itemInputs('4x gtceu:ultra_mana_dust')
        .notConsumable('ctnhcore:horizen_rune')
        .EUt(32678 * 4)
        .duration(100)
    event.recipes.gtceu.magic_fuel_generator('gtceu:mana_up_fuel')
        .outputFluids(Fluid.of('gtceu:mana_up_fuel', 1680))
        .inputFluids(Fluid.of('gtceu:starlight_fuel', 720))
        .inputFluids(Fluid.of('gtceu:blood_fuel', 720))
        .inputFluids(Fluid.of('gtceu:zenith_essence', 720))
        .itemInputs('32x gtceu:gelled_toluene')
        .itemInputs('gtceu:naquadah_dust')
        .itemInputs('4x gtceu:ultra_mana_dust')
        .notConsumable('ctnhcore:horizen_rune')
        .EUt(32678 * 4)
        .duration(100)

    event.recipes.gtceu.magic_fuel_generator('gtceu:mana_up_fuel_active')
        .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 720))
        .inputFluids(Fluid.of('gtceu:mana_up_fuel', 720))
        .outputFluids(Fluid.of('gtceu:mana_up_fuel_active', 720))
        .EUt(32678 * 16)
        .duration(600)

    // event.recipes.gtceu.centrifuge('gtceu:star_fuel_exhausted_recycle')
    //     .EUt(32678 * 4)

    event.recipes.gtceu.centrifuge('gtceu:starlight_fuel_exhausted_recycle')
        .inputFluids(Fluid.of('gtceu:starlight_fuel_exhausted', 1000))
        .outputFluids(Fluid.of('gtceu:starlight_fuel', 100))
        .outputFluids(Fluid.of('gtceu:vibrant_alloy', 400))
        .chancedOutput('2x gtceu:mana_plus_dust', 4000, 2000)
        .chancedOutput('gtceu:mana_super_plus_dust', 4000, 2000)
        .chancedOutput('3x gtceu:small_mana_super_plus_dust', 6000, 2000)
        .EUt(32678)
        .duration(200)

    event.recipes.gtceu.centrifuge('gtceu:mana_up_fuel_exhausted_recycle')
        .inputFluids(Fluid.of('gtceu:mana_up_fuel_exhausted', 1000))
        .outputFluids(Fluid.of('gtceu:blood_fuel', 100))
        .outputFluids(Fluid.of('gtceu:starlight_fuel', 100))
        .outputFluids(Fluid.of('gtceu:zenith_essence', 1000))
        .chancedOutput('2x gtceu:naquadah_dust', 6000, 1000)
        .chancedOutput('4x gtceu:thorium_232_dust', 4000, 2000)
        .EUt(32678 * 4)
        .duration(200)
        //恒星燃料
    event.recipes.gtceu.mana_reactor('gtceu:star_fuel')
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .chancedInput('botania:marimorphosis', 4000, -1250)
        .itemInputs('4x gtceu:naquadria_dust')
        .inputFluids(Fluid.of('gtceu:stellar_alloy', 288))
        .inputFluids(Fluid.of('gtceu:melodic_alloy', 288))
        .inputFluids(Fluid.of('gtceu:end_steel', 288))
        .outputFluids(Fluid.of('gtceu:star_fuel', 576))
        .EUt(32678 * 4)
        .duration(200)
    event.recipes.gtceu.magic_fuel_generator('gtceu:star_fuel')
        .itemInputs('8x gtceu:mana_super_plus_dust')
        .itemInputs('4x gtceu:naquadria_dust')
        .inputFluids(Fluid.of('gtceu:stellar_alloy', 288))
        .inputFluids(Fluid.of('gtceu:melodic_alloy', 288))
        .inputFluids(Fluid.of('gtceu:end_steel', 288))
        .outputFluids(Fluid.of('gtceu:star_fuel', 576))
        .EUt(32678 * 4)
        .duration(100)
    event.recipes.gtceu.mana_reactor('gtceu:star_fuel_active')
        .itemInputs('32x gtceu:ultra_mana_dust')
        .chancedInput('botania:entropinnyum', 4000, -1250)
        .itemInputs('64x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:star_fuel', 1152))
        .inputFluids(Fluid.of('gtceu:adamantite_plasma', 1024))
        .inputFluids(Fluid.of('gtceu:taranium_powder', 1024))
        .outputFluids(Fluid.of('gtceu:star_fuel_active', 1728))
        .EUt(32678 * 8)
        .duration(800)
    event.recipes.gtceu.magic_fuel_generator('gtceu:star_fuel_active')
        .itemInputs('32x gtceu:ultra_mana_dust')
        .itemInputs('64x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:star_fuel', 2304))
        .inputFluids(Fluid.of('gtceu:adamantite_plasma', 2048))
        .inputFluids(Fluid.of('gtceu:taranium_powder', 2048))
        .outputFluids(Fluid.of('gtceu:star_fuel_active', 3456))
        .EUt(32678 * 16)
        .duration(800)
        //未实装燃料
    event.recipes.gtceu.mana_reactor('gtceu:agn_fuel')
        .itemInputs('8x gtceu:aether_dust')
        .itemInputs('8x gtceu:ultra_mana_dust')
        .chancedInput('kubejs:zenith_star', 1000, -1000)
        .notConsumable('kubejs:strongly_interacting_neutron_refector')
        .itemInputs('64x gtceu:industrial_tnt')
        .inputFluids(Fluid.of('gtceu:starmetal_plasma', 1000))
        .inputFluids(Fluid.of('gtceu:eve_plasma', 1000))
        .inputFluids(Fluid.of('gtceu:star_fuel_exhausted', 1000))
        .outputFluids(Fluid.of('gtceu:agn_fuel', 10))
        .EUt(32678 * 128)
        .duration(5)
})