ServerEvents.recipes(event => {

    //魔力电路板配方
    //HV电路增生
    //event.recipes.gtceu.mana_reactor("soc_mana_electronic_circuit")
    //    .itemInputs("kubejs:mana_electronic_circuit")
    //    .itemInputs("4x kubejs:mana_soc")
    //    .itemInputs('2x kubejs:advanced_mana_capacitor')
    //    .itemInputs('2x kubejs:advanced_mana_inductor')
    //    .notConsumable('kubejs:elf_catalyst')
    //    .inputFluids(Fluid.of("gtceu:mana", 5000))
    //    .itemOutputs("kubejs:mana_electronic_circuit")
    //    .chancedOutput("kubejs:mana_electronic_circuit", 8000, 2000)
    //    .chancedOutput("kubejs:mana_electronic_circuit", 6000, 2000)
    //    .chancedOutput("kubejs:mana_electronic_circuit", 4000, 2000)
    //    .chancedOutput("kubejs:mana_electronic_circuit", 2000, 2000)
    //    .chancedOutput("kubejs:mana_electronic_circuit", 1, 2000)
    //    .duration(200)
    //    .EUt(6666)
        //EV电路增生
    //event.recipes.gtceu.mana_reactor('soc_mana_integrated_circuit')
    //    .itemInputs('kubejs:mana_integrated_circuit')
    //    .itemInputs("4x kubejs:zenith_soc")
    //    .itemInputs('16x gtceu:alfsteel_foil')
    //    .itemInputs('4x gtceu:alfsteel_bolt')
    //    .inputFluids(Fluid.of("gtceu:mana", 25600))
    //    .inputFluids(Fluid.of("gtceu:zenith_essence", 800))
    //    .itemOutputs('4x kubejs:mana_integrated_circuit')
    //    .chancedOutput("kubejs:mana_integrated_circuit", 4000, 3000)
    //    .chancedOutput("kubejs:mana_integrated_circuit", 2000, 3000)
    //    .chancedOutput("kubejs:mana_integrated_circuit", 1000, 4000)
    //    .duration(200)
    //    .EUt(14514)

    //天顶soc
    //event.recipes.gtceu.chemical_bath('zenith_soc')
    //    .itemInputs('2x kubejs:mana_soc')
    //    .inputFluids(Fluid.of("gtceu:zenith_essence", 200))
    //    .itemOutputs('kubejs:zenith_soc')
    //    .duration(400)
    //    .EUt(6666)
    //event.recipes.gtceu.cutter('mana_soc_cutter')
    //    .itemInputs('kubejs:mana_wafer')
    //    .inputFluids(Fluid.of("gtceu:mana", 1000))
    //    .itemOutputs('6x kubejs:mana_soc')
    //    .duration(400)
    //    .EUt(7680)
    //event.recipes.gtceu.cutter('zenith_soc_cutter')
    //    .itemInputs('kubejs:zenith_wafer')
    //    .inputFluids(Fluid.of("gtceu:mana", 1000))
    //    .itemOutputs('6x kubejs:zenith_soc')
    //    .duration(800)
    //    .EUt(7680)
    //    //恶魔LUV电路
    event.custom({
            "type": "bloodmagic:altar",
            "altarSyphon": 40000,
            "consumptionRate": 1000,
            "drainRate": 150,
            "input": {
                "item": 'gtceu:micro_processor_computer'
            },
            "output": {
                "item": 'ctnhcore:blooded_micro_processor_mainframe'
            },
            "upgradeLevel": 4
        })
        //恶魔ZPM电路
    //event.recipes.gtceu.hellforge('demon')
    //    .itemInputs('gtceu:nano_processor_computer')
    //    .notConsumable('kubejs:endslate')
    //    .addDataNumber('minimumDrain', 2000)
    //    .addDataNumber('drain', 500)
    //    .itemOutputs('kubejs:will_nano_processor_mainframe')
    //    .EUt(6666)
    //    .duration(200)
        //究极魔力电路基板 UMLHPIC UV魔力电路
    //event.recipes.gtceu.mana_reactor('kubejs:mana_circuit_board')
    //    .itemOutputs('16x kubejs:mana_circuit_board')
    //    .itemInputs('64x gtceu:ultra_mana_foil')
    //    .itemInputs('32x gtceu:reinforced_epoxy_resin_plate')
    //    .itemInputs('ctnhcore:starlight_rune')
    //    .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 16000))
    //    .inputFluids(Fluid.of('gtceu:zenith_essence', 4000))
    //    .EUt(12222)
    //    .duration(2000)
    event.recipes.gtceu.chemical_reactor('kubejs:umlhpic_wafer')
        .itemOutputs('16x kubejs:umlhpic_wafer')
        .itemInputs('32x gtceu:uhpic_wafer')
        .itemInputs('ctnhcore:twist_rune')
        .itemInputs('8x gtceu:ultra_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 4000))
        .inputFluids(Fluid.of('gtceu:elf_fuel', 16000))
        .EUt(32840)
        .duration(2000)
    event.recipes.gtceu.cutter('kubejs:umlhpic_chip')
        .itemInputs('kubejs:umlhpic_wafer')
        .itemOutputs('3x kubejs:umlhpic_chip')
        .inputFluids(Fluid.of('gtceu:mana', 4000))
        .EUt(12222)
        .duration(900)
    event.recipes.gtceu.circuit_assembler('kubejs:magic_quantum_processor_mainframe')
        .cleanroom(CleanroomType.CLEANROOM)
        .itemInputs('gtceu:quantum_processor_mainframe')
        .itemInputs('4x kubejs:umlhpic_chip')
        .itemInputs('kubejs:mana_circuit_board')
        .itemInputs('2x gtceu:ultra_mana_frame')
        .itemOutputs('kubejs:magic_quantum_processor_mainframe')
        .EUt(32840)
        .duration(400)
    event.recipes.gtceu.circuit_assembler('kubejs:magic_quantum_processor_mainframe2')
        .cleanroom(CleanroomType.CLEANROOM)
        .itemInputs('gtceu:crystal_processor_computer')
        .itemInputs('4x gtceu:qbit_cpu_chip')
        .itemInputs('4x kubejs:umlhpic_chip')
        .itemInputs('1x kubejs:mana_circuit_board')
        .itemInputs('2x gtceu:ultra_mana_frame')
        .itemOutputs('kubejs:magic_quantum_processor_mainframe')
        .EUt(32840)
        .duration(200)

})