ServerEvents.recipes(event => {
    //存放着所有类星体之眼配方
    let ctnh = event.recipes.gtceu
    event.recipes.gtceu.assembly_line("quasar")
        .itemInputs('16x ctnhcore:quasar_energy_stabilization_casing')
        .itemInputs('64x gtceu:ultra_mana_octal_wire')
        .itemInputs('64x gtceu:ultra_mana_frame')
        .itemInputs('16x gtceu:mana_plus_gear')
        .itemInputs('16x gtceu:mana_super_plus_gear')
        .itemInputs('8x ctnhcore:ulta_mana_coil_block')
        .itemInputs('64x gtceu:alfsteel_screw')
        .itemInputs('4x bloodmagic:chargingrune2')
        .itemInputs('8x ctnhcore:starlight_rune')
        .itemInputs('8x ctnhcore:twist_rune')
        .itemInputs('4x ctnhcore:horizen_rune')
        .itemInputs('ctnhcore:quasar_rune')
        .itemInputs('8x kubejs:zenith_star')
        .itemInputs('32x ctnhcore:depth_force_field_stabilizing_casing')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 14400))
        .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 144000))
        .inputFluids(Fluid.of('bloodmagic:life_essence_fluid', 144000))
        .inputFluids(Fluid.of('gtceu:enriched_naquadah', 1440))
        .itemOutputs('ctnhcore:eye_of_quasar')
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:mana_generator_turbine_tier4'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(32))
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(800)
        .EUt(524288)
    event.recipes.gtceu.quasar_eye("elf_fuel_2")
        .inputFluids(Fluid.of('gtceu:elf_active_fuel', 8000))
        .outputFluids(Fluid.of('gtceu:mana', 1000))
        .addData("consumption", 100000)
        .addData("tier", 1.5)
        .addData("active", 1)
        .EUt(-150994944 * 2)
        .duration(400)
    event.recipes.gtceu.quasar_eye("elf_fuel_3")
        .inputFluids(Fluid.of('gtceu:starlight_fuel', 8000))
        .outputFluids(Fluid.of('gtceu:mana', 100))
        .addData("consumption", 1000000)
        .addData("tier", 1)
        .addData("active", 1)
        .EUt(-100663296 * 2)
        .duration(400)
    event.recipes.gtceu.quasar_eye("elf_fuel_4")
        .inputFluids(Fluid.of('gtceu:starlight_fuel_active', 8000))
        .outputFluids(Fluid.of('gtceu:starlight_fuel_exhausted', 100))
        .addData("consumption", 1000000)
        .addData("tier", 3)
        .addData("active", 2)
        .EUt(-226492416 * 2)
        .duration(300)
    event.recipes.gtceu.quasar_eye("blood_fuel")
        .inputFluids(Fluid.of('gtceu:blood_fuel', 12000))
        .addData("consumption", 100000)
        .addData("tier", 1)
        .addData("active", 1)
        .EUt(-67108864 * 3)
        .duration(200)
    event.recipes.gtceu.quasar_eye("blood_fuel_active")
        .inputFluids(Fluid.of('gtceu:blood_fuel_active', 30000))
        .outputFluids(Fluid.of('gtceu:blood_fuel_exhausted', 28000))
        .addData("consumption", 10000)
        .addData("tier", 2)
        .addData("active", 2)
        .EUt(-100663296 * 3)
        .duration(480)
    event.recipes.gtceu.quasar_eye('gtceu:mana_up_fuel')
        .inputFluids(Fluid.of('gtceu:mana_up_fuel', 10000))
        .outputFluids(Fluid.of('gtceu:mana', 9000))
        .addData("consumption", 1000000)
        .addData("tier", 4)
        .addData("active", 3)
        .EUt(-150994944 * 2)
        .duration(800)
    event.recipes.gtceu.quasar_eye('gtceu:mana_up_fuel_active')
        .inputFluids(Fluid.of('gtceu:mana_up_fuel_active', 10000))
        .outputFluids(Fluid.of('gtceu:mana_up_fuel_exhausted', 1250))
        .addData("consumption", 2000000)
        .addData("tier", 5)
        .addData("active", 3)
        .EUt(-268435456 * 4)
        .duration(800)
})