ServerEvents.recipes(event => {
    //扭曲聚变
    event.recipes.gtceu.assembly_line("twist_mk2")
        .itemInputs('64x gtceu:ultra_mana_quadruple_cable')
        .itemInputs('gtceu:zpm_fusion_reactor')
        .itemInputs('8x gtceu:luv_fusion_reactor')
        .itemInputs('32x gtceu:fusion_casing_mk2')
        .itemInputs('16x gtceu:fusion_coil')
        .itemInputs('64x kubejs:umlhpic_chip')
        .itemInputs('ctnhcore:twist_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:twisted_fusion_mk2')
        .duration(200)
        .EUt(44444)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:twisted_fusion_mk1'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.ZPM])
            .CWUt(16))
    event.recipes.gtceu.assembly_line("twist_mk3")
        .itemInputs('gtceu:ultra_mana_octal_cable')
        .itemInputs('8x gtceu:zpm_fusion_reactor')
        .itemInputs('gtceu:uv_fusion_reactor')
        .itemInputs('32x gtceu:fusion_casing_mk3')
        .itemInputs('16x gtceu:fusion_coil')
        .itemInputs('64x kubejs:umlhpic_wafer')
        .itemInputs('16x ctnhcore:twist_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 40000))
        .itemOutputs('ctnhcore:twisted_fusion_mk3')
        .duration(200)
        .EUt(88888)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:twisted_fusion_mk2'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UV])
            .CWUt(32))
    event.recipes.gtceu.assembly_line("twist_mkinfinity")
        .itemInputs('64x gtceu:ultra_mana_hex_cable')
        .itemInputs('16x ctnhcore:uv_compressed_fusion_reactor')
        .itemInputs('64x gtceu:fusion_casing_mk3')
        .itemInputs('64x gtceu:fusion_coil')
        .itemInputs('64x kubejs:umlhpic_wafer')
        .itemInputs('64x ctnhcore:twist_rune')
        .itemInputs('64x gtceu:fine_eve_wire')
        .itemInputs('ctnhcore:quasar_rune')
        .inputFluids(Fluid.of('gtceu:eve_plasma', 200000))
        .itemOutputs('ctnhcore:twisted_fusion_mkinfinity')
        .duration(200)
        .EUt(88888)
        .stationResearch(b => b.researchStack(Item.of('ctnhcore:twisted_fusion_mk3'))
            .dataStack(Item.of("gtceu:data_orb"))
            .EUt(GTValues.VA[GTValues.UHV])
            .CWUt(96))
    event.recipes.gtceu.twisted_fusion('ascr')
        .inputFluids(Fluid.of('gtceu:arsenic', 144), Fluid.of('gtceu:chromium', 144))
        .outputFluids(Fluid.of('gtceu:caesium', 144), Fluid.of('gtceu:argon', 1000))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('fen')
        .inputFluids(Fluid.of('gtceu:iron', 144), Fluid.of('gtceu:nitrogen', 1000))
        .outputFluids(Fluid.of('gtceu:neon', 1000), Fluid.of('gtceu:fluorine', 1000))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('kcr')
        .inputFluids(Fluid.of('gtceu:potassium', 144), Fluid.of('gtceu:chromium', 144))
        .outputFluids(Fluid.of('gtceu:carbon', 144), Fluid.of('gtceu:krypton', 1000))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('isn')
        .inputFluids(Fluid.of('gtceu:iodine', 144), Fluid.of('gtceu:tin', 144))
        .outputFluids(Fluid.of('gtceu:sulfur', 144), Fluid.of('gtceu:indium', 144))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('icr')
        .inputFluids(Fluid.of('gtceu:iodine', 144), Fluid.of('gtceu:chromium', 144))
        .outputFluids(Fluid.of('gtceu:carbon', 144), Fluid.of('gtceu:iridium', 144))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('kfe')
        .inputFluids(Fluid.of('gtceu:potassium', 144), Fluid.of('gtceu:iron', 144))
        .outputFluids(Fluid.of('gtceu:fluorine', 1000), Fluid.of('gtceu:trinium', 144))
        .EUt(122880)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('dkr')
        .inputFluids(Fluid.of('gtceu:deuterium', 1000), Fluid.of('gtceu:krypton', 1000))
        .outputFluids(Fluid.of('gtceu:potassium', 144), Fluid.of('gtceu:duranium', 144))
        .EUt(122880)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('tdr')
        .inputFluids(Fluid.of('gtceu:tritium', 1000), Fluid.of('gtceu:duranium', 144))
        .outputFluids(Fluid.of('gtceu:deuterium', 1000), Fluid.of('gtceu:tritanium', 144))
        .EUt(491520)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('npt')
        .inputFluids(Fluid.of('gtceu:nitrogen', 1000), Fluid.of('gtceu:platinum', 144))
        .outputFluids(Fluid.of('gtceu:neutronium', 144), Fluid.of('gtceu:phosphorus', 144))
        .EUt(491520)
        .duration(16);
    event.recipes.gtceu.twisted_fusion('gtceu:mana_up_fuel_active')
        .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 720))
        .inputFluids(Fluid.of('gtceu:mana_up_fuel', 720))
        .outputFluids(Fluid.of('gtceu:mana_up_fuel_active', 720))
        .EUt(32678 * 4)
        .duration(240)
})