ServerEvents.recipes(event => {
    //究极魔力线
    event.recipes.gtceu.centrifuge("mana_fused")
        .itemInputs("4x gtceu:mana_fused_dust")
        .itemOutputs("3x gtceu:mana_steel_dust")
        .itemOutputs("botania:mana_diamond")
        .chancedOutput("gtceu:elementium_dust", 2000, 500)
        .EUt(120)
        .duration(160)
    event.recipes.gtceu.neutron_activator('twist_power_mana')
        .itemInputs('10x gtceu:twist_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 800))
        .itemOutputs('10x gtceu:twist_power_mana_dust')
        .duration(50)
        .addCondition($CTNHRecipes.setNA(800, 1000))
    event.recipes.gtceu.large_chemical_reactor("ctnh:unstable_mana_ok")
        .itemInputs('4x gtceu:mana_plus_dust')
        .notConsumable('kubejs:terria_catalyst')
        .inputFluids(Fluid.of('gtceu:mana', 10000))
        .itemOutputs('4x gtceu:mana_unstable_plus_dust')
        .cleanroom(CleanroomType.CLEANROOM)
        .EUt(1000)
        .duration(10)
    event.recipes.gtceu.large_chemical_reactor("unknow_mana")
        .itemInputs('2x gtceu:mana_super_plus_dust')
        .inputFluids(Fluid.of('gtceu:mana', 1000))
        .inputFluids(Fluid.of('bloodmagic:life_essence_fluid', 1000))
        .inputFluids(Fluid.of('gtceu:krypton', 50))
        .inputFluids(Fluid.of('gtceu:xenon', 150))
        .inputFluids(Fluid.of('gtceu:naquadah', 300))
        .cleanroom(CleanroomType.CLEANROOM)
        .itemOutputs('3x gtceu:unknown_super_mana_dust')
        .EUt(9999)
        .duration(100)
    event.recipes.gtceu.mana_reactor("twist_mana")
        .itemInputs('gtceu:unknown_super_mana_dust')
        .itemInputs('gtceu:thorium_dust')
        .itemInputs('gtceu:uranium_235_dust')
        .itemInputs('gtceu:plutonium_241_dust')
        .notConsumable('kubejs:terria_catalyst')
        .inputFluids(Fluid.of('gtceu:radon', 200))
        .itemOutputs('3x gtceu:twist_mana_dust')
        .EUt(12222)
        .duration(100)
    event.recipes.gtceu.assembler("twist_mana_close")
        .itemInputs('32x gtceu:twist_power_mana_dust')
        .itemInputs('2x gtceu:double_naquadah_plate')
        .itemInputs('16x gtceu:tungsten_carbide_foil')
        .itemOutputs('kubejs:encapsulated_twist_mana')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(1200)
        .EUt(12222)
    event.recipes.gtceu.implosion_compressor("ultra_mana")
        .itemInputs('kubejs:encapsulated_twist_mana')
        .itemInputs('8x gtceu:industrial_tnt')
        .itemOutputs('24x gtceu:ultra_mana_dust')
        .itemOutputs('8x gtceu:mana_remain_dust')
        .duration(10000)
        .EUt(30)
    event.recipes.gtceu.centrifuge('mana_recycle')
        .itemInputs('2x gtceu:mana_remain_dust')
        .chancedOutput('gtceu:mana_fused_dust', 6000, 500)
        .chancedOutput('gtceu:mana_plus_dust', 3000, 500)
        .chancedOutput('2x gtceu:small_mana_super_plus_dust', 1000, 500)
        .outputFluids(Fluid.of("gtceu:mana", 750))
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.mixer("mana_radiation_mixture")
        .itemInputs('3x gtceu:thorium_dust')
        .itemInputs('3x gtceu:uranium_235_dust')
        .itemInputs('3x gtceu:plutonium_241_dust')
        .itemInputs('3x gtceu:naquadah_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 300))
        .notConsumable('kubejs:terria_catalyst')
        .inputFluids(Fluid.of('gtceu:radon', 800))
        .outputFluids(Fluid.of("gtceu:mana_radiation_mixture", 2880))
        .EUt(12222)
        .duration(400)
    event.recipes.gtceu.twisted_fusion('mana_fused')
        .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 64))
        .inputFluids(Fluid.of('gtceu:mana_super_plus', 32))
        .outputFluids(Fluid.of("gtceu:twist_power_mana", 108))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.mana_reactor('mana_stable_plus_dust')
        .itemInputs('10x gtceu:mana_infused_plus_dust')
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 2000))
        .itemOutputs('15x gtceu:mana_stable_plus_dust')
        .EUt(1440)
        .duration(200);
    event.recipes.gtceu.mana_reactor('mana_zenith_plus_dust')
        .itemInputs('8x gtceu:mana_stable_plus_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 200))
        .itemOutputs('8x gtceu:mana_super_plus_dust')
        .EUt(7680)
        .duration(200);
    event.recipes.gtceu.mana_seperator('ma_mixed1')
        .itemInputs('20x gtceu:mana_fused_dust')
        .notConsumable('kubejs:elf_catalyst')
        .itemOutputs('16x gtceu:mana_fused_mixed_dust')
        .itemOutputs('4x gtceu:elementium_dust')
        .itemOutputs('4x gtceu:mana_steel_dust')
        .itemOutputs('2x botania:dragonstone')
        .outputFluids(Fluid.of("gtceu:mana", 1000))
        .duration(800)
        .EUt(480)
    event.recipes.gtceu.chemical_bath('ma_mixed2')
        .itemInputs('4x gtceu:mana_fused_mixed_dust')
        .inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 10000))
        .itemOutputs('3x gtceu:mana_fused_lp_mixed_dust')
        .duration(200)
        .EUt(666)
    event.recipes.gtceu.hellforge('ma_mixed3')
        .itemInputs('16x gtceu:mana_fused_lp_mixed_dust')
        .notConsumable('bloodmagic:etherealslate')
        .itemOutputs('12x gtceu:mana_fused_demon_mixed_dust')
        .addDataNumber('minimumDrain', 2000)
        .addDataNumber('drain', 400)
        .duration(200)
        .EUt(666)
    event.recipes.gtceu.mana_reactor('ma_plus')
        .itemInputs('10x gtceu:mana_fused_demon_mixed_dust')
        .inputFluids(Fluid.of(Fluid.of("gtceu:mana"), 10000))
        .itemOutputs('8x gtceu:mana_plus_dust')
        .duration(100)
        .EUt(1000)
    event.recipes.gtceu.mana_reactor('unstable_plus_dust')
        .itemInputs(['gtceu:mana_unstable_plus_dust', 'botania:rune_mana', 'mythicbotany:midgard_rune'])
        .itemOutputs('gtceu:mana_infused_plus_dust')
        .inputFluids(Fluid.of("gtceu:mana", 100))
        .EUt(1145141919810)
        .duration(60)
        //杂项
    event.recipes.gtceu.greenhouse('tree_turn_big')
        .circuit(20)
        .itemInputs('64x twilightforest:twilight_oak_sapling')
        .itemInputs('64x gtceu:fertilizer')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('twilightforest:hollow_oak_sapling')
        .duration(6400)
        .EUt(120)


    event.recipes.gtceu.mana_seperator('platinum_catalyst2')
        .itemInputs('30x gtceu:platinum_metal_dust')
        .inputFluids(Fluid.of("gtceu:sulfuric_acid", 500))
        .notConsumable('kubejs:terria_catalyst')
        .itemOutputs('10x gtceu:palladium_dust')
        .itemOutputs('12x gtceu:platinum_dust')
        .itemOutputs('9x gtceu:ruthenium_dust')
        .itemOutputs('3x gtceu:rhodium_dust')
        .itemOutputs('4x gtceu:osmium_dust')
        .itemOutputs('3x gtceu:iridium_dust')
        .EUt(8388603)
        .duration(1000)
        .circuit(2);

    event.recipes.gtceu.hellforge("stable")
        .itemInputs('8x ctnhcore:force_field_casing')
        .itemInputs('8x gtceu:tungsten_steel_gear')
        .itemInputs('kubejs:endslate')
        .itemOutputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .addDataNumber('minimumDrain', 2000)
        .addDataNumber('drain', 1000)
        .EUt(10000)
        .duration(600)
    event.recipes.gtceu.hellforge('metal')
        .itemInputs('8x minecraft:amethyst_shard')
        .notConsumable('kubejs:endslate')
        .addDataNumber('minimumDrain', 1000)
        .addDataNumber('drain', 200)
        .itemOutputs('bloodmagic:defaultcrystal')
        .EUt(10000)
        .duration(200)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune')
        .circuit(20)
        .itemInputs('64x ctnhcore:radioactive_waste')
        .itemInputs('botania:overgrowth_seed')
        .itemInputs('64x gtceu:fertilizer')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('ctnhcore:proliferation_rune')
        .duration(20000)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_4')
        .circuit(3)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('16x gtceu:fertilizer')
        .itemInputs('128x ctnhcore:radioactive_waste')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('3x ctnhcore:proliferation_rune')
        .chancedOutput('ctnhcore:proliferation_rune', 9900, 100)
        .chancedOutput('2x ctnhcore:proliferation_rune', 7500, 1500)
        .duration(2000)
        .EUt(24444)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_zenith')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:horizen_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 500))
        .itemOutputs('4x ctnhcore:horizen_rune')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_twist')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:twist_rune')
        .inputFluids(Fluid.of('bloodmagic:life_essence_fluid', 2500))
        .itemOutputs('4x ctnhcore:twist_rune')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_starlight')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:nether_essence_crystal_fluid', 2500))
        .itemOutputs('4x ctnhcore:starlight_rune')
        .duration(200)
        .EUt(12222)
        //组装的各种建筑方块
    event.recipes.gtceu.assembler("twist_frame")
        .itemInputs(['3x gtceu:ultra_mana_plate', '3x gtceu:mana_super_plus_plate', '2x gtceu:double_rhodium_plated_palladium_plate', 'gtceu:osmiridium_frame', 'bloodmagic:defaultcrystal', 'gtceu:fusion_casing'])
        .itemOutputs('1x ctnhcore:twisted_fusion_casing')
        .inputFluids(Fluid.of('gtceu:mana', 500))
        .EUt(30720)
        .duration(200)
    event.recipes.gtceu.assembler("gaia_reactor")
        .EUt(120)
        .duration(200)
        .itemInputs(["4x botania:gaia_ingot", "4x gtceu:solid_machine_casing", "2x gtceu:mv_emitter", "2x botania:mana_diamond", "2x gtceu:terra_steel_screw"])
        .inputFluids(Fluid.of("gtceu:polyethylene", 288))
        .itemOutputs("ctnhcore:gaia_reactor")
    event.recipes.gtceu.assembler("zenith_casing_gearbox")
        .EUt(6666)
        .duration(100)
        .itemInputs('1x gtceu:mana_plus_gear')
        .itemInputs('2x gtceu:mana_plus_plate')
        .itemInputs('2x gtceu:mana_plus_frame')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 400))
        .itemOutputs("2x ctnhcore:zenith_casing_gearbox")
    event.recipes.gtceu.assembler("zenith_mechine_block")
        .EUt(6666)
        .duration(100)
        .itemInputs('2x ctnhcore:blood_casing')
        .itemInputs('2x gtceu:mana_plus_plate')
        .itemInputs('gtceu:mana_plus_frame')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 200))
        .itemOutputs("2x ctnhcore:zenith_casing")
    event.recipes.gtceu.assembler("zenith_eye")
        .itemInputs("2x ctnhcore:mana_steel_casing")
        .itemInputs('2x ctnhcore:alfsteel_casing')
        .itemInputs('2x ctnhcore:terra_steel_casing')
        .itemInputs('2x ctnhcore:force_field_casing')
        .itemInputs('2x gtceu:quantum_eye')
        .itemInputs('2x ctnhcore:depth_force_field_stabilizing_casing')
        .itemInputs('4x gtceu:mana_plus_ingot')
        .inputFluids(Fluid.of("gtceu:zenith_essence", 5000))
        .itemOutputs("1x ctnhcore:zenith_eye")
        .duration(4000)
        .EUt(12222)
    event.recipes.gtceu.assembler("quasar_casing")
        .itemInputs('2x ctnhcore:naquadah_casing_block')
        .itemInputs('4x gtceu:ultra_mana_plate')
        .itemInputs('3x gtceu:neutron_reflector')
        .itemInputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .itemOutputs('4x ctnhcore:quasar_energy_stabilization_casing')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(400)
        .EUt(33333)
    event.recipes.gtceu.assembler("quasar_coil")
        .itemInputs('4x gtceu:naquadah_coil_block')
        .itemInputs('2x gtceu:superconducting_coil')
        .itemInputs('8x gtceu:ultra_mana_double_wire')
        .itemInputs('8x gtceu:neutron_reflector')
        .itemOutputs('8x ctnhcore:ulta_mana_coil_block')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(400)
        .EUt(33333)

    event.recipes.gtceu.assembler('gtceu:fine_eve_wire')
        .itemInputs('64x gtceu:ultra_mana_foil')
        .inputFluids(Fluid.of('gtceu:eve_plasma', 10000))
        .itemOutputs('64x gtceu:fine_eve_wire')
        .EUt(GTValues.VA[GTValues.LV])
        .duration(20000)

    event.recipes.gtceu.mana_reactor('kubejs:zenith_star')
        .itemInputs('gtceu:quantum_star')
        .itemInputs('4x gtceu:ultra_mana_ingot')
        .itemInputs('mythicbotany:vanaheim_rune')
        .itemInputs('ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:mana', 360000))
        .inputFluids(Fluid.of('gtceu:zenith_essence', 90000))
        .itemOutputs('kubejs:zenith_star')
        .EUt(32840)
        .duration(400)
    event.recipes.gtceu.assembler('ctnhcore:mana_lathe')
        .itemOutputs('ctnhcore:mana_lathe')
        .itemInputs('2x gtceu:mv_electric_piston')
        .itemInputs('2x gtceu:mv_lathe')
        .itemInputs('4x #gtceu:circuits/ev')
        .inputFluids('gtceu:mana 1000')
        .EUt(120)
        .duration(400)
    event.recipes.gtceu.assembler('ctnhcore:mana_wiremill')
        .itemOutputs('ctnhcore:mana_wiremill')
        .itemInputs('2x gtceu:mv_electric_piston')
        .itemInputs('4x gtceu:terra_steel_quadruple_wire')
        .itemInputs('4x #gtceu:circuits/ev')
        .inputFluids('gtceu:mana 1000')
        .EUt(120)
        .duration(400)
    event.recipes.gtceu.mana_reactor('ctnhcore:mana_macerator')
        .itemOutputs('ctnhcore:mana_macerator')
        .itemInputs('4x gtceu:mv_macerator')
        .itemInputs('16x gtceu:diamond_grinding_head')
        .itemInputs('64x gtceu:alfsteel_screw')
        .itemInputs('2x gtceu:mv_robot_arm')
        .inputFluids('gtceu:mana 1000')
        .EUt(480)
        .duration(400)

    event.recipes.gtceu.assembler("ctnhcore:mana_mixer")
        .itemInputs('32x gtceu:alfsteel_frame')
        .itemInputs('gtceu:large_mixer')
        .itemInputs('24x ctnhcore:mana_steel_gearbox_casing')
        .itemOutputs('ctnhcore:mana_mixer')
        .EUt(7680)
        .duration(400)
    let ctnh = event.recipes.gtceu


    // ctnh.quasar_create('create_1')
    //     .inputFluids('gtceu:mana_up_fuel_active 100000')
    //     .outputFluids('gtceu:argon_plasma')
    //     .outputFluids('gtceu:helium_plasma')
    //     .outputFluids('gtceu:oxygen_plasma')
    //     .outputFluids('gtceu:nitrogen_plasma')
    //     .outputFluids('gtceu:deuterium')
    //     .outputFluids('gtceu:radon')
    //     .outputFluids('gtceu:tritium')
    //     .outputFluids('gtceu:xenon')
    //     .outputFluids('gtceu:mana 100000')
    //     .outputFluids('gtceu:iron_plasma')
    //     .outputFluids('gtceu:nickel_plasma')
    //     .outputFluids('gtceu:chlorine')
    //     .outputFluids('gtceu:krypton')
    //     .EUt(-10)
    //     .duration(200)
    // ctnh.quasar_create('create_2')
    //     .inputFluids('gtceu:star_fuel_active 10000')
    //     .outputFluids('gtceu:argon_plasma')
    //     .outputFluids('gtceu:helium_plasma')
    //     .outputFluids('gtceu:oxygen_plasma')
    //     .outputFluids('gtceu:nitrogen_plasma')
    //     .outputFluids('gtceu:deuterium')
    //     .outputFluids('gtceu:radon')
    //     .outputFluids('gtceu:tritium')
    //     .outputFluids('gtceu:xenon')
    //     .outputFluids('gtceu:mana 100000')
    //     .outputFluids('gtceu:iron_plasma')
    //     .outputFluids('gtceu:nickel_plasma')
    //     .outputFluids('gtceu:chlorine')
    //     .outputFluids('gtceu:krypton')
    //     .EUt(-1000)
    //     .duration(200)




})