ServerEvents.recipes(event => {
    //究极魔力线
    event.recipes.gtceu.assembler("twist_mana_close")
        .itemInputs('32x gtceu:twist_power_mana_dust')
        .itemInputs('2x gtceu:double_naquadah_plate')
        .itemInputs('16x gtceu:tungsten_carbide_foil')
        .itemOutputs('kubejs:encapsulated_twist_mana')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(1200)
        .EUt(12222)
    event.recipes.gtceu.implosion_compressor("ultra_mana")
        .itemInputs('kubejs:encapsulated_twist_mana')
        .itemInputs('8x gtceu:industrial_tnt')
        .itemOutputs('24x gtceu:ultra_mana_dust')
        .itemOutputs('8x gtceu:mana_remain_dust')
        .duration(10000)
        .EUt(30)
    event.recipes.gtceu.centrifuge('mana_recycle')
        .itemInputs('2x gtceu:mana_remain_dust')
        .chancedOutput('gtceu:mana_fused_dust', 6000, 500)
        .chancedOutput('gtceu:mana_plus_dust', 3000, 500)
        .chancedOutput('2x gtceu:small_mana_super_plus_dust', 1000, 500)
        .outputFluids(Fluid.of("gtceu:mana", 750))
        .duration(100)
        .EUt(960)
    event.recipes.gtceu.mixer("mana_radiation_mixture")
        .itemInputs('3x gtceu:thorium_dust')
        .itemInputs('3x gtceu:uranium_235_dust')
        .itemInputs('3x gtceu:plutonium_241_dust')
        .itemInputs('3x gtceu:naquadah_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 300))
        .notConsumable('kubejs:terria_catalyst')
        .inputFluids(Fluid.of('gtceu:radon', 800))
        .outputFluids(Fluid.of("gtceu:mana_radiation_mixture", 2880))
        .EUt(12222)
        .duration(400)
    event.recipes.gtceu.twisted_fusion('mana_fused')
        .inputFluids(Fluid.of('gtceu:mana_radiation_mixture', 64))
        .inputFluids(Fluid.of('gtceu:mana_super_plus', 32))
        .outputFluids(Fluid.of("gtceu:twist_power_mana", 108))
        .EUt(30720)
        .duration(16);
    event.recipes.gtceu.mana_reactor('mana_stable_plus_dust')
        .itemInputs('10x gtceu:mana_infused_plus_dust')
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 2000))
        .itemOutputs('15x gtceu:mana_stable_plus_dust')
        .EUt(1440)
        .duration(200);
    event.recipes.gtceu.mana_reactor('mana_zenith_plus_dust')
        .itemInputs('8x gtceu:mana_stable_plus_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 200))
        .itemOutputs('8x gtceu:mana_super_plus_dust')
        .EUt(7680)
        .duration(200);
    event.recipes.gtceu.mana_seperator('ma_mixed1')
        .itemInputs('20x gtceu:mana_fused_dust')
        .notConsumable('kubejs:elf_catalyst')
        .itemOutputs('16x gtceu:mana_fused_mixed_dust')
        .itemOutputs('4x gtceu:elementium_dust')
        .itemOutputs('4x gtceu:mana_steel_dust')
        .itemOutputs('2x botania:dragonstone')
        .outputFluids(Fluid.of("gtceu:mana", 1000))
        .duration(800)
        .EUt(480)
    event.recipes.gtceu.chemical_bath('ma_mixed2')
        .itemInputs('4x gtceu:mana_fused_mixed_dust')
        .inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 10000))
        .itemOutputs('3x gtceu:mana_fused_lp_mixed_dust')
        .duration(200)
        .EUt(666)
    event.recipes.gtceu.hellforge('ma_mixed3')
        .itemInputs('16x gtceu:mana_fused_lp_mixed_dust')
        .notConsumable('bloodmagic:etherealslate')
        .itemOutputs('12x gtceu:mana_fused_demon_mixed_dust')
        .addDataNumber('minimumDrain', 2000)
        .addDataNumber('drain', 400)
        .duration(200)
        .EUt(666)
    event.recipes.gtceu.mana_reactor('ma_plus')
        .itemInputs('10x gtceu:mana_fused_demon_mixed_dust')
        .inputFluids(Fluid.of(Fluid.of("gtceu:mana"), 10000))
        .itemOutputs('8x gtceu:mana_plus_dust')
        .duration(100)
        .EUt(1000)
        //杂项
    event.recipes.gtceu.greenhouse('tree_turn_big')
        .circuit(20)
        .itemInputs('64x twilightforest:twilight_oak_sapling')
        .itemInputs('64x gtceu:fertilizer')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('twilightforest:hollow_oak_sapling')
        .duration(6400)
        .EUt(120)


    event.recipes.gtceu.mana_seperator('platinum_catalyst2')
        .itemInputs('30x gtceu:platinum_metal_dust')
        .inputFluids(Fluid.of("gtceu:sulfuric_acid", 500))
        .notConsumable('kubejs:terria_catalyst')
        .itemOutputs('10x gtceu:palladium_dust')
        .itemOutputs('12x gtceu:platinum_dust')
        .itemOutputs('9x gtceu:ruthenium_dust')
        .itemOutputs('3x gtceu:rhodium_dust')
        .itemOutputs('4x gtceu:osmium_dust')
        .itemOutputs('3x gtceu:iridium_dust')
        .EUt(8388603)
        .duration(1000)
        .circuit(2);
    event.recipes.gtceu.hellforge("stable")
        .itemInputs('8x kubejs:force_field_casing')
        .itemInputs('8x gtceu:tungsten_steel_gear')
        .itemInputs('kubejs:endslate')
        .itemOutputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .addDataNumber('minimumDrain', 2000)
        .addDataNumber('drain', 1000)
        .EUt(10000)
        .duration(600)
    event.recipes.gtceu.hellforge('metal')
        .itemInputs('8x minecraft:amethyst_shard')
        .notConsumable('kubejs:endslate')
        .addDataNumber('minimumDrain', 1000)
        .addDataNumber('drain', 200)
        .itemOutputs('bloodmagic:defaultcrystal')
        .EUt(10000)
        .duration(200)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune')
        .circuit(20)
        .itemInputs('64x ctnhcore:radioactive_waste')
        .itemInputs('botania:overgrowth_seed')
        .itemInputs('64x gtceu:fertilizer')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('ctnhcore:proliferation_rune')
        .duration(20000)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_4')
        .circuit(3)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('16x gtceu:fertilizer')
        .itemInputs('128x ctnhcore:radioactive_waste')
        .inputFluids(Fluid.of("minecraft:water", 10000))
        .itemOutputs('3x ctnhcore:proliferation_rune')
        .chancedOutput('ctnhcore:proliferation_rune', 9900, 100)
        .chancedOutput('2x ctnhcore:proliferation_rune', 7500, 1500)
        .duration(2000)
        .EUt(24444)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_zenith')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:horizen_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 500))
        .itemOutputs('4x ctnhcore:horizen_rune')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_twist')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:twist_rune')
        .inputFluids(Fluid.of('bloodmagic:life_essence_fluid', 2500))
        .itemOutputs('4x ctnhcore:twist_rune')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.greenhouse('ctnhcore:proliferation_rune_starlight')
        .circuit(0)
        .itemInputs('ctnhcore:proliferation_rune')
        .itemInputs('ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:nether_essence_crystal_fluid', 2500))
        .itemOutputs('4x ctnhcore:starlight_rune')
        .duration(200)
        .EUt(12222)
    event.recipes.gtceu.assembler("quasar_casing")
        .itemInputs('2x ctnhcore:naquadah_casing_block')
        .itemInputs('4x gtceu:ultra_mana_plate')
        .itemInputs('3x gtceu:neutron_reflector')
        .itemInputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .itemOutputs('4x ctnhcore:quasar_energy_stabilization_casing')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(400)
        .EUt(33333)
    event.recipes.gtceu.assembler("quasar_coil")
        .itemInputs('4x gtceu:naquadah_coil_block')
        .itemInputs('2x gtceu:superconducting_coil')
        .itemInputs('8x gtceu:ultra_mana_double_wire')
        .itemInputs('8x gtceu:neutron_reflector')
        .itemOutputs('8x ctnhcore:ulta_mana_coil_block')
        //.inputFluids(Fluid.of("bloodmagic:life_essence_fluid", 4000))
        .duration(400)
        .EUt(33333)



    event.recipes.gtceu.hellforge('demon')
        .itemInputs('gtceu:nano_processor_computer')
        .notConsumable('kubejs:endslate')
        .addDataNumber('minimumDrain', 2000)
        .addDataNumber('drain', 500)
        .itemOutputs('kubejs:will_nano_processor_mainframe')
        .EUt(6666)
        .duration(200)
    event.recipes.gtceu.assembler('gtceu:fine_eve_wire')
        .itemInputs('64x gtceu:ultra_mana_foil')
        .inputFluids(Fluid.of('gtceu:eve_plasma', 10000))
        .itemOutputs('64x gtceu:fine_eve_wire')
        .EUt(GTValues.VA[GTValues.LV])
        .duration(20000)
    event.recipes.gtceu.mana_reactor('kubejs:mana_circuit_board')
        .itemOutputs('16x kubejs:mana_circuit_board')
        .itemInputs('64x gtceu:ultra_mana_foil')
        .itemInputs('32x gtceu:reinforced_epoxy_resin_plate')
        .itemInputs('ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:mana_stable_cooldown', 16000))
        .inputFluids(Fluid.of('gtceu:zenith_essence', 4000))
        .EUt(12222)
        .duration(2000)
    event.recipes.gtceu.chemical_reactor('kubejs:umlhpic_wafer')
        .itemOutputs('16x kubejs:umlhpic_wafer')
        .itemInputs('32x gtceu:uhpic_wafer')
        .itemInputs('ctnhcore:twist_rune')
        .itemInputs('8x gtceu:ultra_mana_dust')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 4000))
        .inputFluids(Fluid.of('gtceu:elf_fuel', 16000))
        .EUt(32840)
        .duration(2000)
    event.recipes.gtceu.cutter('kubejs:umlhpic_chip')
        .itemInputs('kubejs:umlhpic_wafer')
        .itemOutputs('3x kubejs:umlhpic_chip')
        .inputFluids(Fluid.of('gtceu:mana', 4000))
        .EUt(12222)
        .duration(900)
    event.recipes.gtceu.circuit_assembler('kubejs:magic_quantum_processor_mainframe')
        .cleanroom(CleanroomType.CLEANROOM)
        .itemInputs('gtceu:quantum_processor_mainframe')
        .itemInputs('4x kubejs:umlhpic_chip')
        .itemInputs('kubejs:mana_circuit_board')
        .itemInputs('2x gtceu:ultra_mana_frame')
        .itemOutputs('kubejs:magic_quantum_processor_mainframe')
        .EUt(32840)
        .duration(400)
    event.recipes.gtceu.circuit_assembler('kubejs:magic_quantum_processor_mainframe2')
        .cleanroom(CleanroomType.CLEANROOM)
        .itemInputs('gtceu:crystal_processor_computer')
        .itemInputs('4x gtceu:qbit_cpu_chip')
        .itemInputs('4x kubejs:umlhpic_chip')
        .itemInputs('1x kubejs:mana_circuit_board')
        .itemInputs('2x gtceu:ultra_mana_frame')
        .itemOutputs('kubejs:magic_quantum_processor_mainframe')
        .EUt(32840)
        .duration(200)
    event.recipes.gtceu.mana_reactor('kubejs:zenith_star')
        .itemInputs('gtceu:quantum_star')
        .itemInputs('4x gtceu:ultra_mana_ingot')
        .itemInputs('mythicbotany:vanaheim_rune')
        .itemInputs('ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:mana', 360000))
        .inputFluids(Fluid.of('gtceu:zenith_essence', 90000))
        .itemOutputs('kubejs:zenith_star')
        .EUt(32840)
        .duration(400)
    event.recipes.gtceu.assembler('ctnhcore:mana_lathe')
        .itemOutputs('ctnhcore:mana_lathe')
        .itemInputs('2x gtceu:mv_electric_piston')
        .itemInputs('2x gtceu:mv_lathe')
        .itemInputs('4x #gtceu:circuits/ev')
        .inputFluids('gtceu:mana 1000')
        .EUt(120)
        .duration(400)
    event.recipes.gtceu.assembler('ctnhcore:mana_wiremill')
        .itemOutputs('ctnhcore:mana_wiremill')
        .itemInputs('2x gtceu:mv_electric_piston')
        .itemInputs('4x gtceu:terra_steel_quadruple_wire')
        .itemInputs('4x #gtceu:circuits/ev')
        .inputFluids('gtceu:mana 1000')
        .EUt(120)
        .duration(400)
    event.recipes.gtceu.mana_reactor('ctnhcore:mana_macerator')
        .itemOutputs('ctnhcore:mana_macerator')
        .itemInputs('4x gtceu:mv_macerator')
        .itemInputs('16x gtceu:diamond_grinding_head')
        .itemInputs('64x gtceu:alfsteel_screw')
        .itemInputs('2x gtceu:mv_robot_arm')
        .inputFluids('gtceu:mana 1000')
        .EUt(480)
        .duration(400)
    event.recipes.gtceu.assembly_line('zenith_laser')
        .itemInputs('16x ctnhcore:zenith_casing_gearbox')
        .itemInputs('16x gtceu:mana_plus_gear')
        .itemInputs('4x ctnhcore:depth_force_field_stabilizing_casing')
        .itemInputs('8x gtceu:iv_emitter')
        .itemInputs('2x gtceu:iv_electric_piston')
        .itemInputs('4x gtceu:laser_safe_engraving_casing')
        .itemInputs('4x gtceu:large_engraving_laser')
        .itemInputs('32x gtceu:uhpic_chip')
        .itemInputs('16x gtceu:mana_super_plus_gear')
        .itemInputs('8x ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:twist_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_laser')
        .duration(1200)
        .EUt(12222)
    event.recipes.gtceu.assembly_line("ctnhcore:zenith_circult_assembler")
        .itemInputs('4x gtceu:luv_conveyor_module')
        .itemInputs('32x gtceu:small_mana_super_plus_gear')
        .itemInputs('16x #gtceu:circuits/zpm')
        .itemInputs('16x ctnhcore:zenith_casing_gearbox')
        .itemInputs('8x gtceu:luv_robot_arm')
        .itemInputs('32x gtceu:mana_plus_screw')
        .itemInputs('32x gtceu:naquadah_foil')
        .itemInputs('4x gtceu:large_assembler')
        .itemInputs('16x gtceu:ultra_mana_gear')
        .itemInputs('8x ctnhcore:horizen_rune')
        .itemInputs('4x ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_circult_assembler')
        .EUt(44444)
        .duration(2000)
    event.recipes.gtceu.assembly_line("ctnhcore:zenith_distillation_tower")
        .itemInputs('8x gtceu:luv_electric_pump')
        .itemInputs('12x gtceu:naquadah_large_fluid_pipe')
        .itemInputs('8x #gtceu:circuits/luv')
        .itemInputs('4x ctnhcore:zenith_casing_gearbox')
        .itemInputs('gtceu:large_distillery')
        .itemInputs('32x gtceu:mana_plus_screw')
        .itemInputs('16x gtceu:distillation_tower')
        .itemInputs('4x ctnhcore:horizen_rune')
        .itemInputs('8x ctnhcore:starlight_rune')
        .inputFluids(Fluid.of('gtceu:zenith_essence', 10000))
        .itemOutputs('ctnhcore:zenith_distillation_tower')
        .EUt(12222)
        .duration(800)
    let ctnh = event.recipes.gtceu


    // ctnh.quasar_create('create_1')
    //     .inputFluids('gtceu:mana_up_fuel_active 100000')
    //     .outputFluids('gtceu:argon_plasma')
    //     .outputFluids('gtceu:helium_plasma')
    //     .outputFluids('gtceu:oxygen_plasma')
    //     .outputFluids('gtceu:nitrogen_plasma')
    //     .outputFluids('gtceu:deuterium')
    //     .outputFluids('gtceu:radon')
    //     .outputFluids('gtceu:tritium')
    //     .outputFluids('gtceu:xenon')
    //     .outputFluids('gtceu:mana 100000')
    //     .outputFluids('gtceu:iron_plasma')
    //     .outputFluids('gtceu:nickel_plasma')
    //     .outputFluids('gtceu:chlorine')
    //     .outputFluids('gtceu:krypton')
    //     .EUt(-10)
    //     .duration(200)
    // ctnh.quasar_create('create_2')
    //     .inputFluids('gtceu:star_fuel_active 10000')
    //     .outputFluids('gtceu:argon_plasma')
    //     .outputFluids('gtceu:helium_plasma')
    //     .outputFluids('gtceu:oxygen_plasma')
    //     .outputFluids('gtceu:nitrogen_plasma')
    //     .outputFluids('gtceu:deuterium')
    //     .outputFluids('gtceu:radon')
    //     .outputFluids('gtceu:tritium')
    //     .outputFluids('gtceu:xenon')
    //     .outputFluids('gtceu:mana 100000')
    //     .outputFluids('gtceu:iron_plasma')
    //     .outputFluids('gtceu:nickel_plasma')
    //     .outputFluids('gtceu:chlorine')
    //     .outputFluids('gtceu:krypton')
    //     .EUt(-1000)
    //     .duration(200)




})